# Generated by Django 5.2 on 2025-04-08 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_producto_categoria_producto_codigo_producto_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_coloreable',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CaracteristicaColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_color', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colores', to='products.producto')),
            ],
        ),
    ]
