# Generated by Django 5.2 on 2025-04-08 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0003_producto_es_coloreable_caracteristicacolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='inventario',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.caracteristicacolor'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='products.producto'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='unidades',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
